version: 2
updates:
    # Check for updates to GitHub Actions
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"

    # Maintain dependencies for Swift packages
    - package-ecosystem: "swift"
      directory: "/"
      schedule:
          interval: "weekly"
